### ISSUE TITLE
[BUG] TypeScript error "verifier.verify()" is expecting 4 parameters

### ISSUE THREAD

**Issue by andreifullview** [awslabs/aws-jwt-verify#45]
**Describe the bug**
The package breaks at build

**Versions**
Which version of `aws-jwt-verify` are you using? - aws-jwt-verify@2.1.0
Which version of Node.js are you using? (Should be at least 14) - 16
If using TypeScript, which version of TypeScript are you using? (Should be at least 4) - 4.5.4

**To Reproduce**
```typescript
const verifier = CognitoJwtVerifier.create({
  userPoolId: userPoolId,
  tokenUse: 'id',
  clientId: clientId,
});

const verifierResult = await verifier.verify(token); // it breaks here
```

the error: `semantic error TS2554: Expected 4 arguments, but got 1.`

This breaks only when I build the project. VSCode intelisense doesn't display any issue with the code.

**Comment by ottokruse** [comment]
So far we've only seen this error on TypeScript < 4

Can you tell more about what building the project actually entails in your case? You mean just run `npx tsc`? It does look like that uses a different TypeScript version in your setup than your intellisense uses.

Note that if you use `tsc` (instead of `npx tsc`) you are invoking global TypeScript install, maybe that's what's goes wrong?

**Comment by andreifullview** [comment]
I'm building it with the latest version of tsdx (https://tsdx.io) - https://github.com/jaredpalmer/tsdx

**Comment by ottokruse** [comment]
Any luck @andreifullview ?
